import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <div>

<div className="main">


<div className="header">

   <div className="dashboard">

     <h2>Dashboard</h2>

     <ul className="content">
       <li><a href="/weather">Weather </a></li>
       <li><a href="/Crypto">Crypto </a></li>
       <li><a href="/news">News Updates</a></li>
     </ul>

   </div>

   <div className="dashboard">

     <h2>Details</h2>

     <ul className="content">
       <li><a href="/weatherdetails">City details</a></li>
       <li><a href="/cryptodetails">Crypto details</a></li>
       
     </ul>
   </div>
   


</div>

</div>

    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}

      </body>
    </html>
    </div>
  );
}
